namespace MS.Internal.Interop.DWrite
{
    internal enum DWRITE_FONT_SIMULATIONS
    {
        DWRITE_FONT_SIMULATIONS_NONE = 0x0000,
        DWRITE_FONT_SIMULATIONS_BOLD = 0x0001,
        DWRITE_FONT_SIMULATIONS_OBLIQUE = 0x0002,
    }
}
