// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

//---------------------------------------------------------------------
// <autogenerated>
//
//  Generated by message compiler for wpf (mcwpf.exe)
//
// 
//
//  To update this file run "EventTraceCodeGen.cmd /managed"
//
// </autogenerated>
//---------------------------------------------------------------------
#if !SILVERLIGHTXAML

using System;
using MS.Internal.WindowsBase;

#if SYSTEM_XAML
using System.Xaml;

namespace MS.Internal.Xaml
#else
namespace MS.Utility
#endif
{
    static internal partial class EventTrace
    {
        // [[MCWPF_GENERATE_CODE_HERE]]
    }
}

#endif
