name: Bug Report
description: Create a report to help us improve
labels: []
body:
  - type: markdown
    attributes:
      value: |
        We welcome bug reports! This template will help us gather the information we need to start the triage process.
        Note - If the bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...), please file the issue via the instructions [here](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019).

  - type: textarea
    id: background
    attributes:
      label: Description
      description: Please share a clear and concise description of the problem.
      placeholder: Description
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction Steps
      description: |
        Please include minimal steps to reproduce the problem if possible. Attach or link a project if you have one, even if it is very simple. It helps to quickly evaluate and diagnose the issue and ensures any fix addresses your scenario. If you cannot attach a project, include the smallest possible code snippet, with steps to run it. If possible include text as text rather than screenshots (so it shows up in searches).
      placeholder: Minimal Reproduction
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: |
        Provide a description of the expected behavior.
      placeholder: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: |
        Provide a description of the actual behavior observed. If applicable please include any error messages, exception stacktraces or memory dumps.
      placeholder: Actual behavior
    validations:
      required: true
  - type: textarea
    id: regression
    attributes:
      label: Regression?
      description: |
        Did this work in a previous build or release of .NET Core, or from .NET Framework? If you can try a previous release or build to find out, that can help us narrow down the problem. If you don't know, that's OK.
      placeholder: Regression?
    validations:
      required: false
  - type: textarea
    id: known-workarounds
    attributes:
      label: Known Workarounds
      description: |
        Please provide a description of any known workarounds.
      placeholder: Known Workarounds
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
        label: Impact
        description: |
          Please provide a description of known impact radius, impact intensity and impact reach.
        placeholder: Impact of bug.
    validations:
        required: false

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: |
        Please provide more information on your .NET configuration:
          * Which version of .NET is the code running on?
          * What OS and version, and what distro if applicable?
          * What is the architecture (x64, x86, ARM, ARM64)?
          * Do you know whether it is specific to that configuration?
      placeholder: Configuration
    validations:
      required: false
  - type: textarea
    id: other-info
    attributes:
      label: Other information
      description: |
        If you have an idea where the problem might lie, let us know that here. Please include any pointers to code, relevant changes, or related issues you know of.
      placeholder: Other information
    validations:
      required: false
