#
# Suppress building in this directory unless supporting library - DbgXHelper
# is available to get built.
#
!if exist(..\..\DbgXHelper)
# We found it so build
!INCLUDE $(NTMAKEENV)\makefile.def
!else

clean:

all:

!endif

