// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.
        
#include "Win32Inc.hpp"

#include "src\PrintQueue.cpp"
#include "src\PrintSystemAttributeValueFactory.cpp"
#include "src\PrintSystemNotifications.cpp"
#include "src\PrintSystemAttributeValue.cpp"
#include "src\PrintSystemUtil.cpp"
#include "src\PrintSystemObject.cpp"
#include "src\PrintSystemObjectFactory.cpp"
#include "src\Driver.cpp"
#include "src\Filter.cpp"
#include "src\PrintProcessor.cpp"
#include "src\Port.cpp"
#include "src\ObjectsAttributesValuesFactory.cpp"
#include "src\PrintServer.cpp"
#include "src\InteropPrinterDefaults.cpp"
#include "src\InteropDocInfo.cpp"
#include "src\InteropDevMode.cpp"
#include "src\InteropPrinterInfo.cpp"
#include "src\InteropDriverInfo.cpp"
#include "src\InteropInfoLevelProfile.cpp"
#include "src\InteropJobInfo.cpp"
#include "src\InteropAddJobInfo.cpp"
#include "src\GenericTypeMappings.cpp"
#include "src\GenericPrinterThunkFilter.cpp"
#include "src\GenericPrinterLevelThunk.cpp"
#include "src\GenericDriverThunkFilter.cpp"
#include "src\GenericDriverLevelThunk.cpp"
#include "src\GenericJobLevelThunk.cpp"
#include "src\GenericJobThunkFilter.cpp"
#include "src\GetDataThunkObject.cpp"
#include "src\SetDataThunkObject.cpp"
#include "src\EnumDataThunkObject.cpp"
#include "src\InteropLevelCoverageList.cpp"
#include "src\InteropPrinterInfoUnmanagedBuilder.cpp"
#include "src\InteropPrinterHandler.cpp"
#include "src\XpsDeviceSimulatingInteropPrinterHandler.cpp"
#include "src\XpsCompatiblePrinter.cpp"
#include "src\InternalPrintSystemException.cpp"
#include "src\PrintSystemPathResolver.cpp"
#include "src\LocalPrintServer.cpp"
#include "src\PrintSystemAssemblyInfo.cpp"
#include "src\PrintSystemJobInfo.cpp"
#include "src\LegacyDevice.cpp"
#include "src\GDIExporter.cpp"
#include "src\XPSDocumentWriter.cpp"
#include "src\PremiumPrintStream.cpp"
#include "src\PrintJobSettings.cpp"
#include "src\PrintDocumentImageableArea.cpp"
#include "src\InteropAttributeValueDictionary.cpp"
