name: .NET Core

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '6.0'
      
    - name: Build
      run: .\build.cmd -pack -ci -configuration Debug -prepareMachine /p:Platform=x86
